### ISSUE TITLE
Unknown bug causing julius "Not Responding"

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#221] opened 2020-01-11 10:57 UTC
Test with this save. Load the game and soon delete something.
[test.zip](https://github.com/bvschaik/julius/files/4049241/test.zip)

Reproducible screen recording: https://drive.google.com/open?id=1M7F6qTSCb0k3FJBUCn57CS5OH1jZN9Ep

**Comment by crudelios** [comment] 2020-01-11 13:10
I managed to reproduce this and I'm trying to figure it out.

**Comment by crudelios** [comment] 2020-01-11 19:09
This may be a compiler/optimization bug.

It happens with the builds from bintray, but not with my personal build from MSVC, so I can't reproduce it in my debugger.

Still, I managed to figure out that it seems to happen at the end of the month after deleting something, and the code gets stuck in an endless loop.

So these are the clues for this bug:
- Compiler-specific;
- Happens after deleting something;
- Happens at the end of an in-game month;
- Julius gets trapped in an endless loop.

**Comment by 411752230** [comment] 2020-01-13 04:49
Tested with julius 1.1.0 and 1.0.0, the same occurred. The unknown bug has already existed for a very long time.

**Comment by crudelios** [comment] 2020-01-13 08:12
The bug seems to be related to figures. For some reason, in the provided save file, in `map_figure_delete` at line `58` of `map/figure.c`, the game loads a figure from `grid_offset` ID `32333`, which is an out of bounds value.

Changing the `if`-statement to prevent accessing out-of-bounds figures does not solve the issue, as the game then hangs at a later figure with a valid `grid_offset` but whose `next_figure_id_on_same_tile` is exactly the same `id` as the current figure.

I tried to figure out what caused the figure information to become corrupt but so far I couldn't. It may be a problem with julius or a corrupt savegame, I'm not sure.

**Comment by bvschaik** [comment] 2020-01-13 08:19
Could this be related to #165? That bug, which is also present in C3, was fixed but any saves that are already corrupt will remain that way.

That does not explain the invalid `grid_offset` though.

@411752230 With which version of the game was this save initially created/played?

**Comment by crudelios** [comment] 2020-01-13 08:36
The invalid `grid_offset` is caused by an invalid `f->cross_country_y` being stored in the savegame.

The maximum value of `cross_country_y` should be `2430` (`162 * 15`). However, when the savegame is loaded, it is set to `3104`. Resetting `cross_country_y` to `0` when it is larger to `2430` on load fixes the issue with the savegame.

Why `f->cross_country_y` was saved to `3104` in the first place, I don't know.

**Comment by 411752230** [comment] 2020-01-13 08:52
I got no idea with the version. In fact, this is not a save by me but from C3 heaven: http://caesar3.heavengames.com/downloads/showfile.php?fileid=878&ci=ac6ca082bcdd8d87fa6e30b944d4d478YToxOntpOjA7YToyOntpOjA7czoxNDoiU2VhcmNoIFJlc3VsdHMiO2k6MTtzOjM2OiJsaXN0ZXIucGhwP3N0YXJ0PTAmYW1wO3NlYXJjaD1jeXJlbmUiO319

**Comment by 411752230** [comment] 2020-01-13 08:57
@bvschaik  Yeah, with the MSVC version (no code change at all) provided by @crudelios  , the game runs smoothly.

**Comment by bvschaik** [comment] 2020-01-13 09:22
@411752230 The file you linked to is a scenario, and it's different from the map in the savegame.

The savegame has a (corrupt) figure with figure ID `0`. This figure ID should never be used, since it's used as `null` figure in several places. I'll have a look what we can do about this.

**Comment by 411752230** [comment] 2020-01-13 09:28
> @411752230 The file you linked to is a scenario, and it's different from the map in the savegame.
> 
> The savegame has a (corrupt) figure with figure ID `0`. This figure ID should never be used, since it's used as `null` figure in several places. I'll have a look what we can do about this.

Sorry, I got the wrong link: http://caesar3.heavengames.com/downloads/showfile.php?fileid=534&ci=ac6ca082bcdd8d87fa6e30b944d4d478YToxOntpOjA7YToyOntpOjA7czoxNDoiU2VhcmNoIFJlc3VsdHMiO2k6MTtzOjM2OiJsaXN0ZXIucGhwP3N0YXJ0PTAmYW1wO3NlYXJjaD1jeXJlbmUiO319

**Comment by 411752230** [comment] 2020-01-13 09:35
New discovery: Unable to select the legion flag to move them

**Comment by bvschaik** [comment] 2020-01-13 09:38
> New discovery: Unable to select the legion flag to move them

Please open a new bug for that. I think it's related to yesterday's fixes for the editor menu select.

**Comment by crudelios** [comment] 2020-01-13 17:36
> I'll have a look what we can do about this.

Suggestion: on load, check figure values to see if they are out of bounds, and if so set that specific value to `0`. This may not fix the underlying issues but at least it seems to prevent freezing.

**Comment by bvschaik** [comment] 2020-01-14 15:50
Good news: I managed to reproduce this on my Mac. Just load the .sav and let it run until May. I'll debug this.

**Comment by bvschaik** [comment] 2020-01-14 23:08
I found the culprit. The seagulls, indicating fishing grounds, sometimes migrate off the map. In C3, there seems to be some block of memory after it that clears its data regularly (I suspect fire/damage grids, since there was 1 byte different in one of those when I compared saved games) so that's why C3 does not lock up.

This appears to be fixed by error-checking all grid offsets in `map/figure.c`, at least it does not lock up anymore on my Mac, and comparing saved games from Julius to those from C3 gives no significant changes.
@411752230 Could you test the latest unstable (>= 1.2.0.15) on Windows?

**Comment by crudelios** [comment] 2020-01-14 23:32
So it wasn't just a savegame issue? I never thought it was an active behavior caused by the random nature of the seagull movement.

**Comment by 411752230** [comment] 2020-01-15 04:19
> @411752230 Could you test the latest unstable (>= 1.2.0.15) on Windows?

@bvschaik Thumb, fixed. So many times have I tried with 1.2.0.15-4b95b190 that works fine!

**Comment by bvschaik** [comment] 2020-01-15 07:16
> So it wasn't just a savegame issue? I never thought it was an active behavior caused by the random nature of the seagull movement.

Indeed. The seagulls somehow move off the map. It shouldn't happen but sometimes happens anyway, I have not discovered yet why. When they move off the map they will continue moving around, causing invalid x/y coordinates and therefore invalid grid_offset accesses.

@411752230 Thanks for testing!

**Closed by bvschaik** 2020-01-15 07:16 UTC
