### ISSUE TITLE
Earthquake and Eternal Fires

### ISSUE THREAD

**Issue by jdmillard** [bvschaik/julius#53] opened 2019-01-28 22:59 UTC
Credit of finding this bug goes to my brother. I just helped confirm and reproduce the issue.

When an earthquake happens, buildings are destroyed and set on fire. Everything behaves fine. Then as the fires die out on their own and turn to ash tiles, they convert neighboring quake tiles into ash. Which can then be cleared.

Also, as all the fires die down, a few of them are left burning forever - which is not seen when buildings burn down under normal conditions. The number of tiles that become eternal fires seems nondeterministic - load the same .sav many times. Sometimes there were 8 fires and sometimes there were 9 (maybe dependent on the order that things catch fire?).

Load the attached saved game (which is moments before the earthquake) and you'll see this behavior. Load the same .sav in the original GOG game and see the expected comparison.

[eq test2.sav](https://github.com/bvschaik/julius/files/2805284/eq.test2.zip)

![image](https://user-images.githubusercontent.com/11249742/51872072-38c9f600-2326-11e9-8904-45ad2e3b8f99.png)

**Comment by jdmillard** [comment] 2019-01-28 23:11
Ignore the gardens that was part of my first test and seems to have no effect.

**Comment by crudelios** [comment] 2019-01-29 01:00
Thank you for the provided save file!

It was very useful to help pinpoint the cause of the issue. Should be fixed now.

**Comment by jmillard7** [comment] 2019-01-29 20:31
I'm the brother that found the issue. Nice project btw, very awesome.

**Closed** 2019-01-30 19:57 UTC
