### ISSUE TITLE
Earthquake bug and Forts' Animation

### ISSUE THREAD

**Issue by AzureDragon-1** [bvschaik/julius#69] opened 2019-01-31 16:03 UTC
I was playing a random map of Caesar III. not one from the campaign when at some point an earthquake happened. After the quake was over, instead of the unpassible chasms that are usually left behind after an earthquake, they were replaced by lines of rocks and bushes. Near them there were several unstoppable forever burning houses. Even an iron mine could be put near the newly formed rocks in the places where the quake passed by. 
Again in this mission I noticed that sometimes soldiers from the forts I put down were trembling without any reason especially when the game speed is being increased. I destroyed the fort and even rebuild it several time, but this problem persists. Here is the save file of the map.
[Augusta Trevorum.zip](https://github.com/bvschaik/julius/files/2818044/Augusta.Trevorum.zip)

**Comment by jdmillard** [comment] 2019-01-31 16:15
Do you know what version or commit hash you were running when this happened? The earthquake issue may already be resolved see #53

I've not seen the soldier morale issue, but I'll try to reproduce the issue when I get a chance.

**Comment by AzureDragon-1** [comment] 2019-01-31 17:40
No. I do not know what version I was running. Crudelius send me instructions how to download the latest update a few days ago. I downloaded the latest update on 28.01. or 29.01.2019 and also did it today.
But after this update i reloded the map and the issue was still ON. The soldiers were trembling again on very fast speed and part of the earthquake line was back to normal,but not all of it. Also the everlasting fires were still burning. Even sometimes parts of theatre building or warehouse were shown over the burning fires even though there haven't ever been such buildings.

**Comment by crudelios** [comment] 2019-01-31 18:24
@AzureDragon-1 in that save the earthquake already happened so  it can't be fixed. The fix only applies to new earthquakes unfortunately.

Can you get me the original map so I can confirm everything is fixed?

I also don't understand the "trembling" soldiers. Can you please elaborate?

**Comment by AzureDragon-1** [comment] 2019-01-31 19:49
Hi, here is the map that I played. By "trembling" I meant that the graphic of all the soldiers while they are in the fort trembles and they look like they shiver when the game is played at 500 % speed. This happened to my fort of archers while the legionaires were OK at that speed. They (the legionaires) didn't look like moving. It's like a graphical glitch. 






 >-------- Оригинално писмо --------

 >От: crudelios notifications@github.com

 >Относно: Re: [bvschaik/julius] Earthquake bug and Forts' Animation (#69)

 >До: bvschaik/julius  

 >Изпратено на: 31.01.2019 20:24



 
 
  
 @AzureDragon-1  in that save the earthquake already happened so it can't be fixed. The fix only applies to new earthquakes unfortunately.  
  
Can you get me the original map so I can confirm everything is fixed?  
  
I also don't understand the "trembling" soldiers. Can you please elaborate?

**Comment by AzureDragon-1** [comment] 2019-01-31 20:54
I sent you an e-mail with the file. Did you manage to see the mountains,rocks and bushes over the quake chasms?

**Comment by AzureDragon-1** [comment] 2019-01-31 21:38
Here is the original map I played. 
  Now I am playing it again and soon I'll reach the quake time. I noticed something interesting - I build a fort of javelins and increased the speed after that I lowered it. When the speed is 200 % or 400 % the soldiers stand still on the fort. If I change the speed to 500 % or below 200 %q the graphics of the javelins on the fort begins to shake and shiver and the trmbling effect is produced. Try it and you will see. 
 







 >-------- Оригинално писмо --------

 >От: Bianca van Schaik notifications@github.com

 >Относно: Re: [bvschaik/julius] Earthquake bug and Forts' Animation (#69)

 >До: bvschaik/julius  

 >Изпратено на: 31.01.2019 23:24



 
 
  
Please attach any files to this issue so I can also have a look.  
  
The earthquake issue has been fixed yesterday in  #53 . The fact that you can mine iron and/or marble near the earthquake cracks is a feature also present in Caesar 3.  
  
I'll have a look at the trembling soldiers, though I have a suspicion that it's also present in Caesar 3.

**Comment by AzureDragon-1** [comment] 2019-01-31 21:39
Now I am playing it again and soon I'll reach the quake time. I noticed 
something interesting - I build a fort of javelins and increased the 
speed after that I lowered it. When the speed is 200 % or 400 % the 
soldiers stand still on the fort. If I change the speed to 500 % or 
below 200 %q the graphics of the javelins on the fort begins to shake 
and shiver and the trmbling effect is produced. Try it and you will see.
 








 >-------- Оригинално писмо --------

 >От: crudelios notifications@github.com

 >Относно: Re: [bvschaik/julius] Earthquake bug and Forts' Animation (#69)

 >До: bvschaik/julius  

 >Изпратено на: 31.01.2019 20:24



 
 
  
 @AzureDragon-1  in that save the earthquake already happened so it can't be fixed. The fix only applies to new earthquakes unfortunately.  
  
Can you get me the original map so I can confirm everything is fixed?  
  
I also don't understand the "trembling" soldiers. Can you please elaborate?

**Comment by bvschaik** [comment] 2019-01-31 21:40
Any attachments you send by replying by mail are not uploaded to Github. Please attach them using the web interface.

**Comment by AzureDragon-1** [comment] 2019-01-31 22:15
The e-mail is just for you. I send the original file. In my comment I already uploaded the .sav-file.








 >-------- Оригинално писмо --------

 >От: Bianca van Schaik notifications@github.com

 >Относно: Re: [bvschaik/julius] Earthquake bug and Forts' Animation (#69)

 >До: bvschaik/julius  

 >Изпратено на: 31.01.2019 23:40



 
 
  
Any attachments you send by replying by mail are not uploaded to Github. Please attach them using the web interface.

**Comment by AzureDragon-1** [comment] 2019-01-31 22:17
This is the original map file that i played. 
[Augusta Trevorum.zip](https://github.com/bvschaik/julius/files/2819241/Augusta.Trevorum.zip)

**Comment by AzureDragon-1** [comment] 2019-01-31 22:23
Also I just noticed - onlt the soldiers from the first 3 forts that I build near the entry point are trembling. The other 3 forts I build later on the island across the river were standing still at any speed.

**Comment by jdmillard** [comment] 2019-02-01 00:34
I did another test where I put a fort in each extreme corner of the map. The North corner had normal behavior, I seem to remember that being the 0,0 location. The other 3 corners had the jittery rendering, so it would make sense that they are beyond some threshold on this huge map. We should investigate the military movement logic and see what hard-coded thresholds exist there.

[- blur test2.zip](https://github.com/bvschaik/julius/files/2819605/-.blur.test2.zip)

I third test might be to move the left, right, and bottom forts up gradually to see where the threshold is, then search for that number in the code, but I don't feel like counting tiles lol.

**Comment by AzureDragon-1** [comment] 2019-02-01 18:38
Here is the .sav file just before the earthquake. When the quake happened, the chasms wer OK now and there were no everlasting fires but I didn't have any buildings in the area. So now you may build some building in the region and when the quake comes you may test whether there will be houses that cannot stop burning. I yeasterday installed the latest updates for the mod. But the problem with the legions and soldiers in them is still on the table.
[Augusta Trevorum.zip](https://github.com/bvschaik/julius/files/2822863/Augusta.Trevorum.zip)

**Comment by jdmillard** [comment] 2019-02-02 14:48
@crudelios , the fact that there are 24 "unused" bits following the formation position makes me think that the original game used a 32 bit type. Whether or not we use all 32bits (removing the `__unused_24` logic) or use simply use `unsigned char` to bump our map limit to 255 (keeping the `__unused_24` logic) is up for debate.

I tend to argue in favor of using all 32 (`short`), but there may be a valid case against that. In all honesty I'm not extremely familiar with C types, so if there is conflicting information out there let me know.

**Comment by crudelios** [comment] 2019-02-02 15:03
@jdmillard that may be the case, or those 24 bits may be used for something else. Only @bvschaik can answer that, or if she doesn't know the only solution is to test so we can be certain how changing those values influences the original C3.

**Comment by dalerank** [comment] 2019-02-02 15:10
Just how this variable using in code, as I know julius restores from original exe, also I think programmer dont create empty variables any

**Comment by AzureDragon-1** [comment] 2019-02-02 15:47
I continued playing the map and it seems,after the latest update, after the earthquake, the chasms AGAIN are replaced by mountains and rocks. They were looking for some time as chasms and then again turned into rocks. Here is the .sav file.
[Augusta Trevorum1.zip](https://github.com/bvschaik/julius/files/2824575/Augusta.Trevorum1.zip)

**Comment by crudelios** [comment] 2019-02-02 16:04
@AzureDragon-1 you cannot build on them now, right? @bvschaik if that is the case, that means earthquake tiles must be losing the `plaza` sprite ID somehow.

**Comment by jdmillard** [comment] 2019-02-02 16:32
I ran the campaign mission that has the earthquake and the quake tiles didn't turn to rock. What could cause the difference?

**Comment by AzureDragon-1** [comment] 2019-02-02 22:13
No, I cannot build on them , even the trade caravans bypass them BUT the chasms after the earthquake are supposed to stay like that and NOT turn into rocks. Because the chasms lower the desirability of the nearest area while the rocks do not do so. The chasms' desirability is meant intentionally in the original game and it should stay the same in the mod.

**Comment by jdmillard** [comment] 2019-02-03 04:35
@AzureDragon-1 , I was confused by the recurrence of this issue, so I very carefully executed a few tests using the latest master branch as of 2/2/2019 at 11:36 PM. In the following descriptions, a CLEAN .sav means that it was never touched by Julius, only the official game. JULIUS means it was saved by Julius.exe.

I started Augustus Trevorum (the original .map scenario) in CLEAN GOG Caesar III. I set up a small city with defenses and played all the way up to the earthquake. Here is the save about 1 month before the earthquake: (again, this has not been touched by Julius.exe and the quake has not yet happend at the point when I saved):
[Augusta Trevorum CLEAN PRE-EQ.zip](https://github.com/bvschaik/julius/files/2825171/Augusta.Trevorum.CLEAN.PRE-EQ.zip)
Now load this by Julius and you'll see the earthquake behave perfectly (_if you're using the same version of the code as me_). For future testing, this is the most valuable of the files uploaded in this comment!

I then wondered if perhaps the problem was with saving and loading (data corruption of the way tiles are represented). So I made a CLEAN (GOG) save **AFTER** the eathquake to make sure Julius could load the data and render the existing quake tiles accurately. No issues:
[Augusta Trevorum CLEAN POST-EQ.zip](https://github.com/bvschaik/julius/files/2825172/Augusta.Trevorum.CLEAN.POST-EQ.zip)

I then saved another AFTER QUAKE from JULIUS (where JULIUS executed the quake event) to see if I could load it back into Julius. (To be clear: this was to check that I could save and load to and from Julius after quake tiles are already on map):
[Augusta Trevorum JULIUS POST-EQ.zip](https://github.com/bvschaik/julius/files/2825173/Augusta.Trevorum.JULIUS.POST-EQ.zip)

---

None of these had any issues. Some possible explanation of the issues you are seeing:

1. You are actually using an older version than you think
2. The .sav you have been playing on has had something corrupted in it from being run from several different versions (this feels rather superstitious and unlikely, but I suppose it's possible).
3. ? (I'm open to suggestions)

I loaded the last save you posted and I saw the rocks, but this was after the quake, so I couldn't do much with it test-wise.

**Comment by AzureDragon-1** [comment] 2019-02-03 12:44
@jdmillard Crudelios was so kind to tell me how to get the latest updates for the mod from this site and I did so a few days ago,AFTER the closing of thread #53 .So I assumed that the bug was over. I replayed the map from the beginning after I installed the updates and when the quake happened, I saw tha chasms which stayed like chasms for quite some time while I was playing. Then, when I loaded the game the next day to continue the mission, the chasms were replaced by the rocks again. So I do not have any explanation for this.
I would like to know something : 
1. Is there a chance soon an .exe-file of the mod with ALL the fixed done to be released so that all the users of the mod can get this and re-install the mod from the beginning on clear Caesar 3 GOG version ?
2. If the mod had been introduced in the first place as a COPY OF CAESAR 3 WITH OPEN SOURCE CODE, why are there so many bugs and fixes are needed ? Shouldn't it be just like the original game+some graphical improvements such as the leaving empire message or some new mechanics like the increased speed?

**Comment by AzureDragon-1** [comment] 2019-02-03 12:49
@jdmillard One more thing that may be important-I installed the mod OVER the game installation of Caesar III that didn't come from GOG. I had it for over a a decade and the game version was downloaded from a torrent tracker and then the 1.1 version patch was installed from heavengames.com
So far I haven't experienced any bugs or game failures. I did THE FULL INSTALL OPTION instead of the standart install option when I installed the game.
Still there were no bugs unlike the bugs that GameeZakh reported in his video campaign. And he was using the GOG version.
However I have the GOG-version on my PC.I shall re-install Caesar III using the GOG-file and then we shall see if the glitch persists.
BUT this issue brings up the next question : Is the JULIUS MOD made to be functioning only when installed OVER the GOG -version ???

**Comment by crudelios** [comment] 2019-02-03 13:12
@AzureDragon-1 the reason there are bugs is because julius was readapted more or less from scratch, and since the code is wuite large there were some oversights when adapting things. Also, because the project was more or less unknown, there weren't many people to test for bugs.

**Comment by AzureDragon-1** [comment] 2019-02-03 13:19
If I am reading it right. from the page I download the latest julius modified version. it says that  iam using 
1.0.219 version.

**Comment by jdmillard** [comment] 2019-02-03 13:42
Hmm, if I'm understand correctly, it sounds like the chasm suddenly had used long after the event has long passed. This is interesting.

Echoing what crudelios said: the process that is executed on your machine (Julius.exe) is, for all intents and purposes, practically speaking, unique code that is unrelated to the original code in every way. However, it was designed to :
* Have save game compatibility
* Load images, movies, and sounds of the original game
* Mirror the logic of the original game (meaning that a given map that progresses N years without any human input and is then saved by C3 should have the exact same output.sav  (bits and bytes, 0s and 1s) as the same city after N years in Julius.)

So yes, it's *supposed* to be the exact same, but it's still being tested. I don't think that a torrented version would behave differently, but????? Crudelios would have better insight about that than me.

 Also, _I loaded your most recent .sav in the original clean game and it had the rocks - which means the damage has been done to that .sav file and loading it from different versions likely isn't going to revert it back chasm tiles_. What needs to be figured out is  what caused the corruption in the first place. It's possible that the Julius saving logic is bugged and those tiles were losing the plaza sprites like crudelios mentioned... But I didn't see that in my test. So my (admittedly short, quick) test was probably insufficient for testing the validity of the save/load logic).

**Comment by crudelios** [comment] 2019-02-04 15:37
I reproduced @AzureDragon-1 's issue by rotating the map immediately after the earthquake. All the cracks magically converted to rock textures.

**Comment by bvschaik** [comment] 2019-02-04 20:32
Good one @crudelios, found and fixed: updating the rocks on map rotate was missing an "is not plaza/earthquake" check.

**Comment by bvschaik** [comment] 2019-02-04 20:46
@AzureDragon-1 I think all problems in your report have been fixed now. Can you test [this version](https://ci.appveyor.com/project/bvschaik/julius/builds/22118707/job/o0naarwud673fiis/artifacts) to confirm that the soldiers are OK and the earthquake cracks behave normally as well? If you have a savegame with rocks instead of earthquake lines, you can rotate the map to fix them.

**Comment by AzureDragon-1** [comment] 2019-02-04 21:00
Yes, I've just tested this using my latest .sav file. When I rotate he map, the rocks change back to chasms. And the soldiers don't tremble any more.
Thank you for your fast reaction in solving this annoying bug. If I detect something unusual from now on. I will inform you. The next step for me will be to play or create another map with an earthquake event and to see if this thing with the rocks happens again and if it does, whether the rotation of the map will fix it.
This is the.sav file I used for testing a few moments before winning the map.
[Augusta Trevorum1.zip](https://github.com/bvschaik/julius/files/2829794/Augusta.Trevorum1.zip)

**Comment by bvschaik** [comment] 2019-02-04 21:21
Thanks for confirming :smiley:
If you find anything else, just open another issue, preferably one for each problem you find. This one had two unrelated problems, which makes it harder for us to keep track of what's fixed and what still needs attention.

**Closed by bvschaik** 2019-02-04 21:21 UTC
