### ISSUE TITLE
Cart pushers sometimes passing granary

### ISSUE THREAD

**Issue by Rijk** [bvschaik/julius#412] opened 2020-04-13 16:08 UTC
Hi, check out the following save file: [Aedile 13.sav.zip](https://github.com/bvschaik/julius/files/4470369/Aedile.13.sav.zip)

I set up a granary near the wharfs to collect all the fish. The granary in the bottom of the map is set to Getting food and so will pick it up from the top one. I've tested this save file in the original Caesar III, and it works as expected.

In Julius however, the cart pushers sometimes pass the granary (as if it is full) to walk onto the next granary, which is way farther for them:

![image](https://user-images.githubusercontent.com/159500/79136406-3fb91900-7db1-11ea-9f67-8fbcf4abbbc5.png)

I think this is a bug, especially considering the difference in behaviour with the original game.

**Comment by bvschaik** [comment] 2020-04-13 18:06
Thanks for your report, I'll have a closer look since I indeed see a deviation from Caesar 3, but I'm not sure if it's related to the granaries. The granary you mention often loses its employees due to poor access to houses. During the period of no employment, any fisherman that spawn will ignore that granary. I see the same happening in Caesar 3.

**Comment by bvschaik** [comment] 2020-04-13 19:24
Upon a closer look I found a corrupted tile which was causing the differences I saw when comparing the saved games from C3 and Julius after letting it run for a game month. Other than that, the behaviour of C3 and Julius is exactly the same with respect to the granaries: it's caused by losing employees every now and then.

Since this is also present in C3, I'm closing this issue.

**Closed by bvschaik** 2020-04-13 19:24 UTC
Labels: bug

**Comment by Rijk** [comment] 2020-04-13 20:18
Thanks for the quick reply. Happy Easter!
