### ISSUE TITLE
Plaza with Aqueduct weirdness

### ISSUE THREAD

**Issue by TheRealAyCe** [bvschaik/julius#466] opened 2020-05-25 11:33 UTC
Fancy Road = Road+"Plaza?" not sure what the english word is, it's "Platz" in german.

The game shows you that you can build an aqueduct on top of a fancy road, but you can't (green, but clicking does nothing).

I also had it happen that a completely hidden road was created. Even though nothing showed on the tile, I couldn't place anything there. I first placed the road, then the fancy upgrade, then deleted the tile, there it is. Rotating or placing other stuff fixes it.
![weird2](https://user-images.githubusercontent.com/11407231/82809566-b0615400-9e8c-11ea-8234-df319ac018bc.jpg)

Another bug: when you place the missing aqueduct tile, it will do this:
![weird1](https://user-images.githubusercontent.com/11407231/82809295-15687a00-9e8c-11ea-8d40-721b48ff2077.jpg)

**Comment by crudelios** [comment] 2020-05-25 12:21
I've compared all your bugs to the original C3:

> The game shows you that you can build an aqueduct on top of a fancy road, but you can't (green, but clicking does nothing).

C3 also shows green, however it does warn that you "Must build on clear land", which Julius doesn't. So that needs to be addressed.

> I also had it happen that a completely hidden road was created.

I'm not being able to reproduce this. What exact steps did you take? Which order did you build things on?

> Another bug: when you place the missing aqueduct tile, it will do this:

This is a bug with the original C3 as well. You aren't supposed to be able to build an aqueduct over a road ending, however you can prolong the road first, build the aqueduct and then delete the extra road tiles. That results in an unintended tile state that, when you add an aqueduct intersection, makes a wrong image show up (in this case, the gatehouse top). Since this one is original behaviour, it won't be fixed in Julius.

**Comment by bvschaik** [comment] 2020-06-07 12:38
The aqueduct-turned-into-roadhouse bug is fixed. I think we tackled all oddities now, so I'm closing the issue. Thanks for reporting!

**Closed by bvschaik** 2020-06-07 12:38 UTC
Labels: bug, original bug
