### ISSUE TITLE
Bridge reconstruction

### ISSUE THREAD

**Issue by iulianiliescu** [bvschaik/julius#49] opened 2019-01-26 09:18 UTC
You can't place a new bridge where one has been deleted already.

1. Build a bridge
2. Delete it
3. Attempt to build a new bridge in the same location
4. The square where the game will attempt to put the other end of the bridge will be the middle of the water.

Between the docks and the reservoir, near the lumber industry, you will see one graden on each side of the river, that is the place of a former bridge, which I can't rebuild anymore.

[savegame.zip](https://github.com/bvschaik/julius/files/2798813/savegame.zip)

**Comment by iulianiliescu** [comment] 2019-01-26 09:19
Also the fact when you demolish a bridge, it only demolishes the portion you clicked on, it's kind of annoying.

**Comment by crudelios** [comment] 2019-01-26 13:33
It's indeed a bug, which happens only when the bridge itself (excluding its ramps) is one tile wide.

I'll try to fix it when I have time.

**Comment by siredmar** [comment] 2019-01-26 17:20
Fixed the bug. See pull request #50

**Comment by crudelios** [comment] 2019-01-28 09:39
Siredmar I'm afraid I don't agree  with the proposed bugfix. Treating all road tiles with sprites as bridges doesn't seem correct to me.

Contrary to what I said before, the bug happens on all ship bridges, regardless of its length. Also, it doesn't happen on the original Caesar 3.

Upon some investigation, I realized the bug happens because some tiles of the bridge are being assigned sprite id 0 (which means no sprite). More specifically, in lines 114 to 118 of `map\bridge.c`, in function `map_bridge_get_sprite_id`, there is the following code:

```
if (is_ship_bridge) {
    if (index == 1 || index == length - 2) {
        // platform after ramp
        return 0;
}
```

This happens because the first and last tiles of a ship bridge are set to the "bridge platform" sprite, and its image occupies two tiles. Therefore, no sprite needs to be drawn on the tiles `bridge start + 1` and `bridge end - 1`.

However, function `map_is_bridge` only returns true if the tile in question is a water tile and there is a sprite in that tile (meaning, the sprite id is other than 0). Because there are no sprites in those tiles, the function returns false and other functions that depend on it (such as the bridge demolition routine) get sent incorrect bridge length sizes.

I'm not entirely sure about what I'm saying, but I guess that the bridge tile in question should be assigned sprite id 13. Sprite 13 doesn't get drawn in `widget\city_bridge.c`, suggesting that it should be used precisely for those tiles. Also, in function `map_routing_update_water` of file `map\routing_terrain.c`, sprite 13 specifically doesn't allow ships to pass, which seems correct given that the platform image appears to be of insuficcient height to allow ships to go through. Also, it seems curious that there is a check for sprite 13, when it is never currently set in `map_bridge_get_sprite_id` (while all other sprite ids, from 1 to 15, are).

So my suggestion to fix this bug would be to change line 117 of  `map\bridge.c` from `return 0;` to `return 13;`.
In my (extremely not throught) test, doing so fixed the demolition bug without any visual changes. It should also improve the pathfinding by not allowing ships to pass under that platform.

In an unrelated note, this also makes me believe that there is a bug with ship bridges and ship pathfinding, but that is a case for another issue.

**Comment by siredmar** [comment] 2019-01-28 18:52
Hi crudelios,
while debugging i found that the routine `map_is_bridge` didn't quite get the expected results. 

What i did was: looking at the `map_bridge_add` method and unwinding stuff made there.
In particular: `map_bridge_add` adds for the selected grid `TERRAIN_ROAD`. 
The method also adds the desired sprites (both ramps, bridge parts, ...).

So for me it was just fine to look if the bridge itself. It's clear that the method `map_bridge_remove` method gets called when a bridge shall be removed. So no need to look at the sprites anymore. 
As the `map_bridge_add` method adds the `TERRAIN_ROAD` flag to the grid it should be sufficient to just iterate over the grids that match that `TERRAIN_ROAD`.

Just to explain where my thoughts came from.

I can however confirm that your solution also works by just adding a return > 0.
I guess i'm just not that familiar with the codebase yet.

I updated my pull request.

**Comment by bvschaik** [comment] 2019-01-28 19:20
I can confirm that @crudelios is entirely correct. @siredmar I just merged your PR. Thanks both for figuring this out.

I'm back from holiday so I'll look over the remaining pull requests this week.

**Closed** 2019-01-28 19:20 UTC

**Comment by crudelios** [comment] 2019-01-28 19:35
About that.. I have a pull request ready to submit if you want :P

**Comment by bvschaik** [comment] 2019-01-28 19:52
Add it to the pile ;) (and thanks for all the work you're putting in, much appreciated)

**Comment by crudelios** [comment] 2019-01-28 20:13
If I knew about this project sooner, I would have helped sooner! This is great.

More big changes incoming, I'm implementing DPI awareness (I'll explain why when I submit the pull request) and it's going to be a big one.
