### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by MarkusCicero** [bvschaik/julius#609] opened 2021-05-31 17:08 UTC
Hello!
I noticed some problems with the sound in the game. Hiss are heard when playing event clips and occasionally game sounds. Could this be a problem due to the fact that I have an old audio card C-Media PCI Audio Device PCI 8738?

**Comment by crudelios** [comment] 2021-05-31 19:03
Hi, this is actually an issue I've been trying to fix.

Can you please try this test build from augustus to see if the issue is fixed? (the video volume is disabled so it will be at max volume)

http://public.josecadete.net/C3/augustus-new-sdl.zip

**Comment by crudelios** [comment] 2021-06-01 09:37
Fixed in 14faa68.

**Closed by crudelios** 2021-06-01 09:37 UTC
Labels: bug
