### ISSUE TITLE
AppImage does not work - libtinfo.so.5 is not packaged

### ISSUE THREAD

**Issue by jxjxjhjh** [bvschaik/julius#515] opened 2020-09-15 01:29 UTC
linux manjaro
appimaes
Applications

1.下载c3
2.下载julius*.appimage
3.run julius*.appimage
不会启动程序

**Comment by crudelios** [comment] 2020-09-15 13:08
After translating the question, it seems to be a duplicate of #510.

**Comment by jxjxjhjh** [comment] 2020-09-15 14:45
> After translating the question, it seems to be a duplicate of #510.

我的问题是，我不知道游戏目录应该放在哪里，我放在 /home/jxjxjhjh/Applications/c3 并没有用

**Comment by jxjxjhjh** [comment] 2020-09-15 15:06
> 翻译问题后，似乎是[＃510](https://github.com/bvschaik/julius/issues/510)的重复项。

通过终端运行确定问题是缺少两个库
./ju*appimage

error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

yay -S libtinfo5

error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

yay -S libselinux 

OK!

manjaro gnome 20.0.3 mini

**Comment by crudelios** [comment] 2020-09-15 16:22
@bvschaik May not be a duplicate after all. Maybe some missing appimage dependencies? I don't have enough knowledge about appimages to help :/

**Comment by bvschaik** [comment] 2020-09-15 20:59
@crudelios I'll have a look tomorrow. I still have the Manjaro virtual machine from trying to reproduce #510.

**Comment by bvschaik** [comment] 2020-09-16 08:00
I can reproduce this starting with the dev AppImage from August 31. Something changed in the build so that it doesn't include some libraries anymore. I'm investigating how this happened and how to fix.

Missing libraries:

- /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
- /lib/x86_64-linux-gnu/libtinfo.so.5
- /lib/x86_64-linux-gnu/libselinux.so.1
- /lib/x86_64-linux-gnu/liblzma.so.5
- /lib/x86_64-linux-gnu/libgcrypt.so.20
- /lib/x86_64-linux-gnu/libnsl.so.1

**Comment by bvschaik** [comment] 2020-09-16 14:06
@jxjxjhjh Could you try the [latest version](https://bintray.com/bvschaik/julius-dev/linux/_latestVersion#files)?

I reverted to the previous version of `linuxdeploy`, which is used to create the AppImage, as a temporary measure. I have created a [bug report](https://github.com/linuxdeploy/linuxdeploy/issues/145) for LinuxDeploy, hopefully we can fix this properly upstream.

**Comment by bvschaik** [comment] 2020-09-22 12:08
The bug in LinuxDeploy has been fixed: the AppImage is generated correctly again.

**Closed** 2020-09-22 12:07 UTC
Labels: bug
