### ISSUE TITLE
Suggestions on saving governer's name and default name of auto-saving

### ISSUE THREAD

**Issue by 411752230** [bvschaik/julius#212] opened 2020-01-07 15:28 UTC
1.Saving governer's name:

There are some delicate differences about saving governer's name between C3 and Julius. By watching the governer's name in city constrcution kit mode, in C3, everytime you launch c3.exe or c3_mapper.exe will reset the name to "the new governer" except loading a saved game with a governer name already existed, after which starting a new career will be the name you used in the last saved game you loaded, which means you can switch the name freely by loading a saved game. While in julius, relaunching the game will not lost your saved name except starting a new career, but starting a new career will always reset the name to "the new governer". Moreover, once you got a name saved in julius, you cannot switch the name as your wish unless starting a new career to reset again.

Suggestion: Picking up the advantages both of C3 and julius, relaunching game will not reset name; loading game can switch name.

2.Default names of auto-saving when there is no same saved game already existed:

By comparison between the Chinese C3.exe and English C3.exe, I used the cheat code to pass all the missions. Here are the screenshots below. In the Chinese version, the added ordinals makes the mission number much more clear, compared with which the English saved games are sorted by Names causing disorder of the missions.

![QQ截图20200107230108](https://user-images.githubusercontent.com/14128007/71905735-b8517d80-31a3-11ea-831f-49104491c22f.jpg)
![QQ截图20200107231615](https://user-images.githubusercontent.com/14128007/71905745-bbe50480-31a3-11ea-9d95-8ab5391ec59e.jpg)

Suggestion: Adopting the ordinals as the Chinese version. In addition, playing city construction kit mode will auto-save the game as "My Rome" rather than "Citizen" by default.

**Comment by 411752230** [comment] 2020-01-08 10:21
@bvschaik 1. new bug. Load this saved game whose governer's name is Jack Chen. Then Replay the Map. The name becomes none
![QQ截图20200108181259](https://user-images.githubusercontent.com/14128007/71969994-bd193e80-3242-11ea-9cc7-906dd16777b6.jpg)
[test.zip](https://github.com/bvschaik/julius/files/4034750/test.zip)

2. Another small one. Go to this screen and then switch out and minimize the game. The background picture disappears.
![QQ截图20200108181649](https://user-images.githubusercontent.com/14128007/71970475-bccd7300-3243-11ea-90ff-b15bc09c1bc4.jpg)

**Comment by crudelios** [comment] 2020-01-08 12:33
> 1. new bug. Load this saved game whose governer's name is Jack Chen. Then Replay the Map. The name becomes none

Confirmed here.

> Another small one. Go to this screen and then switch out and minimize the game. The background picture disappears.

That's an old one, I've been thinking about ways to fix that but never got to implement anything.

**Comment by bvschaik** [comment] 2020-01-09 22:17
The replay map bug has been fixed in 1.2.0.

The second one is more difficult: that's just the way screens work in Julius, and also in Caesar 3: a dialog like the file dialog will be drawn over the previous screen. Then if the window size changes or the buffer is refreshed, just the dialog is drawn and not the screen behind it. Fixing this is hard because the file dialog does not know which screen it's supposed to draw behind it: you can access it from the main menu, but also from within your city.

**Comment by 411752230** [comment] 2020-01-18 16:33
> The second one is more difficult: that's just the way screens work in Julius, and also in Caesar 3: a dialog like the file dialog will be drawn over the previous screen. Then if the window size changes or the buffer is refreshed, just the dialog is drawn and not the screen behind it. Fixing this is hard because the file dialog does not know which screen it's supposed to draw behind it: you can access it from the main menu, but also from within your city.

The second one also happens by pressing F6 switching between fullscr and windowed.

**Comment by TheRealAyCe** [comment] 2020-01-22 13:36
Wasn't the governor name bug fixed in a patch for C3? Maybe the patch was not available for your language version?

**Comment by 411752230** [comment] 2020-01-22 14:18
> Wasn't the governor name bug fixed in a patch for C3? Maybe the patch was not available for your language version?

No. My suggestion has no business with the language version.

**Comment by crudelios** [comment] 2020-02-11 22:48
After reading through this again, I don't think loading a saved game should change the name you've set the last time you started a career. Because of that, I have many funny names in cities I've built, since I happened to load someone else's city before.

The best solution would be to allow your name to be changed in the main menu without having to start a new career. However that would require adding yet another button to the main menu, which isn't lacking buttons already.

I would suggest such an implementation be added to [Keriew's fork](https://github.com/Keriew/julius) for now.

In fact, the whole idea can be expanded to something like Pharaoh's family. But instead of families, we would have careers here.

Regarding the ordinals before the names: I agree it would be easier to find.

Regarding saving CCK cities as `My Rome`: they could be saved as the city name itself and with a `CCK` prefix. Example: `CCK Caesarea`.

**Comment by 411752230** [comment] 2020-02-12 00:22
> After reading through this again, I don't think loading a saved game should change the name you've set the last time you started a career. Because of that, I have many funny names in cities I've built, since I happened to load someone else's city before.
> 
> The best solution would be to allow your name to be changed in the main menu without having to start a new career. However that would require adding yet another button to the main menu, which isn't lacking buttons already.
> 
> I would suggest such an implementation be added to [Keriew's fork](https://github.com/Keriew/julius) for now.
> 
> In fact, the whole idea can be expanded to something like Pharaoh's family. But instead of families, we would have careers here.
> 
> Regarding the ordinals before the names: I agree it would be easier to find.
> 
> Regarding saving CCK cities as `My Rome`: they could be saved as the city name itself and with a `CCK` prefix. Example: `CCK Caesarea`.

After a thorough experience and reading your post, I have thought about the name again. Yeah, you are right, switching name by loading a game does have some shoddy disadvantages.

As you said about the CCK, your idea would be much more better.

**Comment by bvschaik** [comment] 2020-02-21 14:04
Reading through the comments, it looks like all issues have been resolved. Regarding the governor name: the way it works now is the best we can do without requiring people to enter their name again when starting a CCK mission.

**Closed by bvschaik** 2020-02-21 14:04 UTC

**Comment by 411752230** [comment] 2020-02-21 18:19
> Reading through the comments, it looks like all issues have been resolved. Regarding the governor name: the way it works now is the best we can do without requiring people to enter their name again when starting a CCK mission.

@bvschaik @crudelios Yes, it is. Would there be a optimazation for the save's name? Or it woule be added to Keriew's fork?

**Comment by crudelios** [comment] 2020-02-21 20:34
@bvschaik not that there is no limit to the number of saves perhaps we can think about improving autosave names.
