### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by NotMe12** [bvschaik/julius#48] opened 2019-01-24 18:52 UTC
Program crashes and fails to respond on startup screen stating 'Click to start'. 

![image](https://user-images.githubusercontent.com/47008386/51701055-7e29b300-2008-11e9-9615-becf6e4b3a8f.png)

This is with the English GOG version freshly reinstalled. Monitor resolution is 1920 x 1080. After restarting computer it allowed me to play for roughly 10 minutes before it crashed in the same fashion, but actually in game this time.

Since then it will not let me proceed past the screen in the screenshot before it crashes again, as it did when first installed. 

Readout from julius-log.txt reads as follows:

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Creating screen 1920 x 1080, fullscreen? 1

INFO: Texture created (1920 x 1080)

INFO: model loaded

Thanks for your time!

**Comment by crudelios** [comment] 2019-01-25 15:02
When the game works for 10 minutes and then hangs, does a mouse click cause the hang?

**Comment by NotMe12** [comment] 2019-01-25 15:05
I believe it may do? I have certainly been in the process of doing something so whether it was just timed rightly I cannot say, but I believe I did click the mouse just before.

**Comment by crudelios** [comment] 2019-01-26 14:33
This seems to be an SDL event issue, however I don't know if it's a problem on your end or with the game as I can't reproduce your issue!

**Comment by NotMe12** [comment] 2019-01-26 14:36
Is there anything I can do or try in order to solve it?

**Comment by crudelios** [comment] 2019-01-26 23:41
You can try loading the game in a different computer to check if the problem persists. Also, what is your version of Windows?

**Comment by NotMe12** [comment] 2019-01-27 16:35
Latest version, I believe. I updated it earlier today and it made no difference. Be interesting if anyone else has this problem and whether they can sort it out or not.

**Comment by crudelios** [comment] 2019-01-28 19:21
I'm at a loss with your problem... Have you tried redownloading the game + SDL libraries?

**Comment by NotMe12** [comment] 2019-01-28 20:06
So I've downloaded the zip without the .exe in that you have to do the console commands with. Unfortunately I don't fully understand how to do it to create the .exe. What does "After cloning the repo" mean? And then do I just execute the commands in the cmd prompt whilst inside that directory?

Also I don't know whether you think I should try the method of "GOG version with InnoExtract" instead and see if that changes anything?

Thanks!

**Comment by crudelios** [comment] 2019-01-31 10:01
@NotMe12 there is now a link at the main page to grab the latest version, so you don't need to compile it yourself.

Please try a newer build, maybe one of them will somehow fix your issue.

**Comment by NotMe12** [comment] 2019-02-01 14:45
@crudelios I have downloaded and tried the newest version and it has not made any difference at all. Exactly the same issue as before. Looks like i'll have to settle for just the widescreen mod.

**Comment by crudelios** [comment] 2019-02-01 15:44
@NotMe12 before quitting, please test this custom build:

https://ci.appveyor.com/api/buildjobs/a95fh44jok4tbmgh/artifacts/julius.zip

If the app hangs, try to resize the window if possible.

**Comment by jdmillard** [comment] 2019-02-02 02:34
This is a wild guess, but here it goes:

Could it be that NotMe12 has another version of SDL on his system (put there by some other app a long time ago). If such libraries are in the PATH, then we might never know that they are being used.

The counter argument might be that the local folder dlls take priority over directories in the PATH. But I don't know if that is the case. (I don't know standard windows .exe rules).

**Comment by crudelios** [comment] 2019-02-02 09:41
It is very well a possibility, but AFAIK DLLs in the local directory are always loaded if found, DLLs in the PATH come second.

Since the zip file has both the exe and the DLLs, I always assumed all of them were copied. That's what's in the instructions at least.

I'm inclined to think this is a problem with event polling. For some reason the events are not being processed. Either that or the mouse click event is causing an endless loop for some reason...

**Comment by NotMe12** [comment] 2019-02-02 12:19
@crudelios Having tried the build you suggested it happened almost immediately after starting a map. This time however the game doesn't crash it just freezes with no error message. Have tried resizing window to no avail and the crash effectively freezes the program in the foreground with no way of forcing it to shut. Log now shows:

INFO: Initializing SDL

INFO: SDL initialized

INFO: Loading game from working directory

INFO: Creating screen 1920 x 1080, fullscreen? 1

INFO: DPI changed. Scaling window by 1.000000

INFO: Texture created (1920 x 1080)

INFO: model loaded

**Comment by NotMe12** [comment] 2019-02-03 15:45
Can only get to the main menu after PC has been rebooted. It does let me past as many times as I want to, as long as I don't actually play the game to the point of crashing. Once it gets to the freeze moment, even if I can shut the game I cannot subsequently get past the screen before the menu that says "Click to start" anymore.

**Comment by crudelios** [comment] 2019-02-04 13:46
@NotMe12 I'll prepare a special build today that logs everything so I can better pinpoint what may be causing this.

If you haven't done so already, can you try not playing in fullscreen? Press F9 for a 1024x768 window and try to see how the game behaves that way.

**Comment by NotMe12** [comment] 2019-02-08 20:40
Thanks for sticking with this Crudelios, apologies for the delay in replying. Interestingly playing it non full-screened (pressing F9) runs fine constantly without any problems. 

Will be trying the new version tomorrow and will be able to give feedback and the zipped log file when and if things go awry, but hopefully the fact that it works non full-screened may give you something to go on.

**Comment by crudelios** [comment] 2019-02-08 21:41
Thanks for the report!

Out ot curiosity, when the game crashed was the window maximized?

**Comment by NotMe12** [comment] 2019-02-08 21:45
Unfortunately not, it was still at the size of the window when you press F9.

**Comment by crudelios** [comment] 2019-02-08 21:48
Back to square one, then...

Just to make sure everything is tested, can you follow the instructions posted on my answer to issue #92? Perhaps using an older SDL version will fix your problem as well!

**Comment by devnoname120** [comment] 2019-02-16 10:21
@NotMe12 Can you try with the latest version? I had this issue previously but updating seemed to fix it.

**Comment by bvschaik** [comment] 2019-03-15 18:35
Closing this, I suspect a driver problem which is impossible to debug from our end.
@NotMe12 If you are still experiencing this, please try the suggestions from crudelios and devnoname120.

**Closed by bvschaik** 2019-03-15 18:35 UTC
