### ISSUE TITLE
Quality of Life Improvements and Remasters

### ISSUE THREAD

**Issue by KillahNeo** [bvschaik/julius#206] opened 2020-01-01 21:47 UTC
![RIP-remaster](https://user-images.githubusercontent.com/47231209/71757476-064d4500-2e75-11ea-89c3-89f01e551869.png)

Quality of Life Improvements:

- Adding a button to come back to the main menu when you're already in a scenario and also a button to go back to the main menu when you click to load a scenario, and maybe tweak the ESC menu to have that option as well other than just quitting the game.

- Maybe a option to play .smk videos from the menu as well

- A tool to create custom translations for the game

- Add back the game intro .smk videos please or make it optional at least

- Load the main-menu with the resolution according to the user's desktop

- Enable the game to load custom .mp4 instead of .smks so i can insert remastered videos, or find a way to render .smk files.

Remasters:

- I have already remastered the 40 in-game pre and post game screenshots, the pictures have been enhanced from 1024 pixels to 1920.
_________________________________________________________________________________________________________________________________________
![test6-remaster](https://user-images.githubusercontent.com/47231209/71646052-f04a5380-2cbf-11ea-8a09-d0649e09eda2.jpg)
Mission 3
_________________________________________________________________________________________________________________________________________
![test37-remaster](https://user-images.githubusercontent.com/47231209/71646290-ad3eaf00-2cc4-11ea-945f-a73018742e7e.jpg)
Old Caesar III Setup Img
_________________________________________________________________________________________________________________________________________

- I'm not sure if it is copyrighted but i have all the MP3 Files previously available at the old Caesar III Website, they have been downloaded by my father in 1999, so they're not the web crawler 1 Mb versions, and I'd like to make them available for everyone.

But that's not all, I'd like to tweak the resolution of the actual game buildings, characters, videos, UI elements, etc, so I'm here telling you guys that whenever the time comes I'm ready to do some work.

Steam for contact: https://steamcommunity.com/id/killahneo/

**Comment by KillahNeo** [comment] 2020-01-01 22:08
Just a bonus for the fans:
![Roman Empire-remaster](https://user-images.githubusercontent.com/47231209/71646719-0c52f280-2cca-11ea-830a-c388d70ac4f6.jpg)

**Comment by 411752230** [comment] 2020-01-02 01:36
Amazing！Good Work Bro! This is exactly what I imagine for too.

**Comment by crudelios** [comment] 2020-01-02 15:29
> Ading a button...

Seems like a good idea.

> Maybe a option to play .smk videos from the menu as well

I don't see why this would be needed, smk's can already be played on media player classic home cinema

> A tool to create custom translations for the game

I think such a tool already exists, it was created by @bvschaik 

> Add back the game intro .smk videos please or make it optional at least

Definitely possible to implement, although disabled by default

> Load the main-menu with the resolution according to the user's desktop

I don't understand this. Do you mean if the desktop resolution is lower than the monitor resolution?

> Enable the game to load custom .mp4 instead of .smks so i can insert remastered videos, or find a way to render .smk files.

This *might*

**Comment by bvschaik** [comment] 2020-01-02 16:01
> Adding a button to come back to the main menu when you're already in a scenario and also a button to go back to the main menu when you click to load a scenario, and maybe tweak the ESC menu to have that option as well other than just quitting the game.

You mean File -> New Game?

> >  A tool to create custom translations for the game
> 
> I think such a tool already exists, it was created by @bvschaik

Yes, it just needs a (very big) overhaul to support Chinese: https://github.com/bvschaik/citybuilding-tools. Be aware that any translations are limited by the character set supported by the game version you have. No Greek letters in Russian game versions, no Russian letters in Latin1 (Western Europe) game versions, etc.

> Add back the game intro .smk videos please or make it optional at least

Why? I find it very annoying to have to click through 3 videos I've already watched dozens of times when I want to start the game.

> Load the main-menu with the resolution according to the user's desktop

Julius already remembers the previously used window size?

> Enable the game to load custom .mp4 instead of .smks so i can insert remastered videos, or find a way to render .smk files.

No. I'm currently looking into the video code for the libsmacker licensing issue: it's hard enough to support one type of video. Opening up the whole world of mp4 codecs (and including them in Julius) is not worth the effort.

**Comment by KillahNeo** [comment] 2020-01-02 20:54
> Yes, it just needs a (very big) overhaul to support Chinese: https://github.com/bvschaik/citybuilding-tools. Be aware that any translations are limited by the character set supported by the game version you have. No Greek letters in Russian game versions, no Russian letters in Latin1 (Western Europe) game versions, etc.

Do you have a release version i can use?

> Add back the game intro .smk videos please or make it optional at least

By default games have an option to disable those intros but they're not the main option, they're optional, so it should be that way on Julius, or at least make it optional so people can choose to keep the intro videos etc, after all the intro was made for a reason and for first time users maybe it would be cool to showcase it. 

> This might be doable, in time. Libsmacker has a program that converts each frame of a video file to a bmp image, which can then be rescaled. If you want, I can give you the program.

Yes i want it, add me on steam please.

> No. I'm currently looking into the video code for the libsmacker licensing issue: it's hard enough to support one type of video. Opening up the whole world of mp4 codecs (and including them in Julius) is not worth the effort.

To remaster the videos i'd need to make the game load them, and i cannot render them into .smk files, so we'd need the game to support another type of format.

> Maybe a option to play .smk videos from the menu as well

It would be just a nice feature to have, Diablo II for example has the same feature

![image](https://user-images.githubusercontent.com/47231209/71692169-f277e500-2d87-11ea-8511-03de267378b2.png)

And add a button to go back to the main menu from this screen.
![image](https://user-images.githubusercontent.com/47231209/71692513-db85c280-2d88-11ea-9488-605886854c26.png)

**Comment by KillahNeo** [comment] 2020-01-02 20:56
Besides, this main menu picture and everything really could be re-sized to fit the desktop resolution accordingly, maybe do a background picture slideshow instead of a static image aswell, that's a great UI change though.

![image](https://user-images.githubusercontent.com/47231209/71692584-10921500-2d89-11ea-8c34-7c59d0013644.png)

**Comment by KillahNeo** [comment] 2020-01-02 20:57
A button to go back from here aswell
![image](https://user-images.githubusercontent.com/47231209/71692638-446d3a80-2d89-11ea-95e5-70b853a008ca.png)

**Comment by KillahNeo** [comment] 2020-01-02 21:05
The ESC (Escape) button menu could contain all the info listed from those two areas on the left upper corner, it would look somenthing like this

- Go back to the Main Menu
- Restart the map
- Load a game
- Save a game
- Options - (Video Options - Audio Options - Game Velocity - Game Difficulty)
- Exit the game

![image](https://user-images.githubusercontent.com/47231209/71692842-cd847180-2d89-11ea-85d2-3935b2da08c7.png)

I can make a sketch to see how it would look in Caesar III Aesthetics.

**Comment by bvschaik** [comment] 2020-01-02 21:54
> A button to go back from here aswell
> ![image](https://user-images.githubusercontent.com/47231209/71692638-446d3a80-2d89-11ea-95e5-70b853a008ca.png)

You can right-click there to go back.

**Comment by bvschaik** [comment] 2020-01-02 21:57
> The ESC (Escape) button menu could contain all the info listed from those two areas on the left upper corner, it would look somenthing like this
> 
>     * Go back to the Main Menu
> 
>     * Restart the map
> 
>     * Load a game
> 
>     * Save a game
> 
>     * Options - (Video Options - Audio Options - Game Velocity - Game Difficulty)
> 
>     * Exit the game
> 
> 
> ![image](https://user-images.githubusercontent.com/47231209/71692842-cd847180-2d89-11ea-85d2-3935b2da08c7.png)
> 
> I can make a sketch to see how it would look in Caesar III Aesthetics.

Why, though? That would be a major overhaul of the way windows work in Julius. Besides, the Escape menu should not contain every action on every screen ("difficulty options" has no use in the editor, to name something). Plus, devices without keyboard (vita, switch, android) will not be able to access those actions.

**Comment by bvschaik** [comment] 2020-01-02 22:01
> Do you have a release version i can use?

See the releases section there.

> add me on steam please.

I'm not allowed to do that with my limited account.

> To remaster the videos i'd need to make the game load them, and i cannot render them into .smk files, so we'd need the game to support another type of format.

Do you know how complex video codecs are? Mp4 is a container format only, which can contain video and audio streams in a variety of formats. Supporting those will bloat Julius with dozens of additional DLLs (on Windows) and a lot of dependencies on Linux/Mac. And for what? For a few people who may like better videos...

> And add a button to go back to the main menu from this screen.
> ![image](https://user-images.githubusercontent.com/47231209/71692513-db85c280-2d88-11ea-9488-605886854c26.png)

True. I can add right-click-to-go-back support there as well.

**Comment by KillahNeo** [comment] 2020-01-02 22:35
> Why, though? That would be a major overhaul of the way windows work in Julius. Besides, the Escape menu should not contain every action on every screen ("difficulty options" has no use in the editor, to name something). Plus, devices without keyboard (vita, switch, android) will not be able to access those actions.

They could access if you replace the two tabs with one button which opens this new tab that i've mentioned, i think it would look more updated to modern standards.

> You can right-click there to go back.

Still, a button there wouldn't hurt, for example i dind't knew i could right-click to go back

Just a "<<" on the corner would do

> Do you know how complex video codecs are? Mp4 is a container format only, which can contain video and audio streams in a variety of formats. Supporting those will bloat Julius with dozens of additional DLLs (on Windows) and a lot of dependencies on Linux/Mac. And for what? For a few people who may like better videos...

Im handing out ideas on how to improve the game, but if you think it is way too complex and not worth the effort i understand

> I'm not allowed to do that with my limited steam account.

Give me your steam profile link and i'il add you myself

**Comment by KillahNeo** [comment] 2020-01-02 23:11
Just a mock-up of what i have in mind
![image](https://user-images.githubusercontent.com/47231209/71698886-fada1b00-2d9b-11ea-803c-20b247d168bd.png)

**Comment by KillahNeo** [comment] 2020-01-02 23:31
![image](https://user-images.githubusercontent.com/47231209/71699556-ddf31700-2d9e-11ea-8bd3-65a0991f9637.png)
This little guy here could be used as the population icon.

**Comment by KillahNeo** [comment] 2020-01-02 23:48
mockup of what i have in mind
![mockup](https://user-images.githubusercontent.com/47231209/71700027-2c091a00-2da1-11ea-91bc-e70108dacf10.jpg)

**Comment by KillahNeo** [comment] 2020-01-02 23:54
example of remaster
![caesar_3](https://user-images.githubusercontent.com/47231209/71700212-00d2fa80-2da2-11ea-9eed-7dac4276eb95.png)

**Comment by 411752230** [comment] 2020-01-03 03:29
> mockup of what i have in mind
> ![mockup](https://user-images.githubusercontent.com/47231209/71700027-2c091a00-2da1-11ea-91bc-e70108dacf10.jpg)

Nice PS. lol To be simple, adopt the UI of Emperor?

**Comment by KillahNeo** [comment] 2020-01-03 19:41
> Nice PS. lol To be simple, adopt the UI of Emperor?

It's a mix between the Emperor game which is also a Impressions Game and Age of Empires II ESC Menu.

That's probably how Caesar III would look it it was made in 2003 instead of 1998.
So it wouldn't be considered far just random inventions, it sticks to what could have been, the devil is in the details and I'm sure doing these small changes would be great for modernizing the game.

**Comment by KillahNeo** [comment] 2020-01-03 20:31
Small Update:
![image](https://user-images.githubusercontent.com/47231209/71747605-db4ffa80-2e4e-11ea-8cca-45a3e1b8d425.png)

**Comment by crudelios** [comment] 2020-01-03 20:35
I have to say, those look great.

**Comment by KillahNeo** [comment] 2020-01-03 20:39
> I have to say, those look great.

Thanks, like i said, i would like to be in charge of remastering every single aspect of the game in terms of art etc, i just need you guys to tell me which files need to be done and afterwards just implement my changes, i have a lot of ideas UI wise, i'm not sure if they're difficult to change BUT i know they would certainly look a million times better if they did, for example the main menu resolution, can that be changed easily?

**Comment by KillahNeo** [comment] 2020-01-04 01:03
Update on game's logo
![RIP-remaster](https://user-images.githubusercontent.com/47231209/71757457-da31c400-2e74-11ea-8722-d42d4be3ee2b.png)

**Comment by KillahNeo** [comment] 2020-01-04 02:05
New Main-Game menu ? @bvschaik 
![RIP6mainmenu](https://user-images.githubusercontent.com/47231209/71758373-7fe93100-2e7d-11ea-885e-a52b44a1e7a3.jpg)

**Comment by KillahNeo** [comment] 2020-01-04 02:15
Here's the remastered main-menu picture if anyone wants it
![RIP4-remaster](https://user-images.githubusercontent.com/47231209/71758479-e589ed00-2e7e-11ea-8f1c-a54aa3c8345b.jpg)

**Comment by devnoname120** [comment] 2020-01-04 23:58
> 
> 
> Small Update:
> ![image](https://user-images.githubusercontent.com/47231209/71747605-db4ffa80-2e4e-11ea-8cca-45a3e1b8d425.png)

Which tool did you use in order to produce the images? Some deep learning upscaler I presume?

**Comment by KillahNeo** [comment] 2020-01-05 05:11
> Which tool did you use in order to produce the images? Some deep learning upscaler I presume?
Private tool + photoshop experience

**Comment by KillahNeo** [comment] 2020-01-05 07:12
Yet another remaster attempt

![remaster attempt - Copia](https://user-images.githubusercontent.com/47231209/71776500-78a34f80-2f71-11ea-932d-a90d45da7262.jpg)


Original for comparision

![test13](https://user-images.githubusercontent.com/47231209/71776507-88229880-2f71-11ea-8bd7-8a980127fc98.jpg)

**Comment by KillahNeo** [comment] 2020-01-05 19:59
Ladies and Gentlemen, i present you the Caesar III Demo Main Menu graphics remastered

![main menu demo-remaster](https://user-images.githubusercontent.com/47231209/71785270-71fdf200-2fdc-11ea-84ec-21a1c52e0c23.jpg)

This menu was used on the cover art for the game release in most European countries
![549728-caesar-iii-windows-manual](https://user-images.githubusercontent.com/47231209/71785283-893cdf80-2fdc-11ea-9e2d-ce4b4922d530.jpg)

Instead of the original one which is 
![12_front](https://user-images.githubusercontent.com/47231209/71785285-9063ed80-2fdc-11ea-86c9-416d6fa3edcc.jpg)

Speaking of which i've remasted this picture aswell
![nova capa2](https://user-images.githubusercontent.com/47231209/71785297-a96c9e80-2fdc-11ea-8f3f-0b262ec6d099.jpg)

**Comment by bvschaik** [comment] 2020-01-05 21:06
Hi @KillahNeo, those remastered images really look great!

Unfortunately, changing the graphics in Julius is no easy task. The graphics are currently loaded from the sg2 files present in Caesar 3, which cannot be easily changed. Adapting the code to load graphics from elsewhere, or using any graphics other than the ones currently in the set of images supplied by C3 is very difficult. I expect that we would have to rewrite about half of the game (half of 75.000 lines of code) to support it, which will take over a year. I have already spent 11 years on Julius; I don't have the time nowadays to either implement or oversee other people implementing the necessary changes.

Besides that, I would like Julius to be as close to C3 as possible graphics-wise, so it can be used as drop-in replacement. Large-scale changes of the interface would best be done in a fork of Julius.

Perhaps you can find some developers to fork Julius and implement the changes?
Again, I really like the sharp images, but implementing them in the current codebase is simply too much work.

**Comment by crudelios** [comment] 2020-01-05 21:41
There were talks about remastering the game before. Even I got upscaled versions of some images using an AI, which look good although not as good as @KillahNeo's.

The problem is indeed the change needed to the code. Because julius re-creates C3, it uses an old codebase. The code is very interlinked, and all of the drawing code and UI elements are hard-coded into the game.

This makes it very hard to change UI elements without messing something else up in the game. I've been there: for example, when I tried to improve tooltip performance I created many crashes in seemingly unrelated places.

A remaster of the game would indeed mean a "recoding" of the entire game, which is extremely time-consuming.

Besides, that seems to go beyond the main idea behind julius, which was to recreate the game in open-source in order to allow some improvements and support for modern platforms.

I would certainly like to see a more modern approach to julius and C3, but it doesn't seem possible right now.

**Comment by KillahNeo** [comment] 2020-01-06 04:01
That's very unfortunate, maybe if CAESAR IA was picked up we'd be able to do the changes i've proposed, too bad that project is dead since 2016.

**Comment by KillahNeo** [comment] 2020-01-06 20:22
Maybe ... Caesar's new icon?

![icone](https://user-images.githubusercontent.com/47231209/71846311-06ce2180-30a9-11ea-8ec4-d8042a03cdd8.png)

**Comment by crudelios** [comment] 2020-01-07 09:34
> Maybe ... Caesar's new icon?

Humm... I actually like the current icon (the coin)!

-----------------------------------

![back_button](https://user-images.githubusercontent.com/6518876/71884743-c7e3ae80-3130-11ea-9cdd-f8af6cbf44da.png)

I think this back button can be added to some menus, at least to the "New carreer" and "City Construction Kit".

**Comment by dalerank** [comment] 2020-01-07 09:44
> > Small Update:
> > ![image](https://user-images.githubusercontent.com/47231209/71747605-db4ffa80-2e4e-11ea-8cca-45a3e1b8d425.png)
> 
> Which tool did you use in order to produce the images? Some deep learning upscaler I presume?

seems like ESRGAN work. Is't it?

**Comment by shirakaba** [comment] 2020-01-07 11:12
> > Which tool did you use in order to produce the images? Some deep learning upscaler I presume?
> 
> Private tool + photoshop experience

The fact that the tool involved is private (and unnamed) worries me about the licensing of the images. Also, as an open-source effort, it seems risky to undertake if you're the only one who has the tools to contribute to this. A remaster to a higher resolution is essentially all-or-nothing, so everything would be riding on you.

> Adapting the code to load graphics from elsewhere, or using any graphics other than the ones currently in the set of images supplied by C3 is very difficult.

I'm wondering whether it would be practical to make a tool that could swap out graphics from the sg2 files, but:

> The graphics are currently loaded from the sg2 files present in Caesar 3, which cannot be easily changed.

If someone could produce a way to easily change the sg2 files, maybe we could get away with no code changes, but that would only be true if the graphics were staying at the same resolution. A remastered graphics would be produced at a higher resolution, and I can imagine that there are a not-insignificant number of places in the codebase where C3 originally assumed fixed sizes for these graphics, so it does sound like a big rewrite would be involved.

Unless I'm mistaken about either of those previous points, I would have to agree that this is far out of scope, and I agree with @bvschaik:

> Perhaps you can find some developers to fork Julius and implement the changes?
> Again, I really like the sharp images, but implementing them in the current codebase is simply too much work.

---

A wild idea just popped into my head which I might as well share. I doubt that current technology is up to doing it sufficiently well, but would it be viable to run a filter (as a separate app) that sits over the game and runs the intelligent upscaling in real-time? This wouldn't do much for those backgrounds like the main menu (they would still have a black background filling in all the space bordering the image), but it could be of benefit for the city view. Just throwing ideas around.

**Comment by 411752230** [comment] 2020-01-07 11:23
Hey bros. Would it be possible for you to modify a C3 logo of traditional Chinese for the simpified Chinese C3? There is only one char should be changed as I have been working for the new simplified Chinese C3 here #192 
![C3](https://user-images.githubusercontent.com/14128007/71889214-9f81a180-317c-11ea-83e4-304da8a55f0d.png)

As the picture above, 凱 is a traditional Chinese char whose simplfied counterpart is 凯. I extrated the picture by sgreader.
What I need would be the change of the bottom left of the char to the simplified one with its oiginal resolution unchanged
![QQ截图20200107184927](https://user-images.githubusercontent.com/14128007/71890281-e5d80000-317e-11ea-960b-618b97ffa738.jpg)

@bvschaik Is it feasible to replace a logo of C3title.555 which is the first picture I mentioned above.
[TC C3title.zip](https://github.com/bvschaik/julius/files/4030282/TC.C3title.zip)

By the way, it is amazing to see bvschaik has succesfully make julius identify the traditional Chinese with the process name changed to 凱撒大帝. Maybe we need to change the process name as well as the logo to 凯撒大帝 for the newer Simplifeid Chinese individually. Instead of c3.eng as identification of traditional Chinese to load the font rome.555, C3title.555 might make it easier?

**Comment by KillahNeo** [comment] 2020-01-08 07:21
> seems like ESRGAN work. Is't it?

No

> The fact that the tool involved is private (and unnamed) worries me about the licensing of the images. Also, as an open-source effort, it seems risky to undertake if you're the only one who has the tools to contribute to this. A remaster to a higher resolution is essentially all-or-nothing, so everything would be riding on you.

Yes

> A wild idea just popped into my head which I might as well share. I doubt that current technology is up to doing it sufficiently well, but would it be viable to run a filter (as a separate app) that sits over the game and runs the intelligent upscaling in real-time? This wouldn't do much for those backgrounds like the main menu (they would still have a black background filling in all the space bordering the image), but it could be of benefit for the city view. Just throwing ideas around.

No

> Hey bros. Would it be possible for you to modify a C3 logo of traditional Chinese for the simpified Chinese C3? There is only one char should be changed as I have been working for the new simplified Chinese C3 here #192

Can you create a new .555 file?

**Comment by KillahNeo** [comment] 2020-01-08 21:20
Enjoy everyone
https://www.youtube.com/watch?v=EeXufjqCAy0

**Comment by 411752230** [comment] 2020-01-09 09:41
> > Hey bros. Would it be possible for you to modify a C3 logo of traditional Chinese for the simpified Chinese C3? There is only one char should be changed as I have been working for the new simplified Chinese C3 here #192
> 
> Can you create a new .555 file?

I am sure @bvschaik can who has created a new rome.555 (A picture with font) for Simplified Chinese font

**Comment by KillahNeo** [comment] 2020-01-09 19:51
> I am sure @bvschaik can who has created a new rome.555 (A picture with font) for Simplified Chinese font

She told me she doesn't have an software to write stuff on the game though.

**Comment by bvschaik** [comment] 2020-01-09 22:18
I don't have software to change arbitrary images in SG2 files. However, replacing C3Title.555 is a piece of cake if it remains the same size.

**Comment by KillahNeo** [comment] 2020-01-11 19:11
Can you make Julius arbitrary change the main menu picture randomly each time you start the game?

If yes, i can provide you the caesar iii demo main menu picture and each time you load the game it could load the demo and the retail version randomly, it's already in the .555 format

**Comment by KillahNeo** [comment] 2020-01-11 19:13
And a nice addition would be a language selector inside the game.

**Comment by bvschaik** [comment] 2020-01-15 20:54
We've established that remastering the game is not feasible.
Of your other suggestions, the intro videos have been added, you can now right-click to go back on the CCK screen, and an issue for adding a back button has been created (#225), so I'm closing this.

**Closed by bvschaik** 2020-01-15 20:54 UTC
